package io.lin.reader.ui.theme.color

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import io.lin.reader.ui.theme.AppThemePalette


object DefaultTheme : AppThemePalette {
    private val primaryLight = Color(0xFF00677D)
    private val onPrimaryLight = Color(0xFFFFFFFF)
    private val primaryContainerLight = Color(0xFFB2EBFF)
    private val onPrimaryContainerLight = Color(0xFF004E5E)
    private val secondaryLight = Color(0xFF4B626A)
    private val onSecondaryLight = Color(0xFFFFFFFF)
    private val secondaryContainerLight = Color(0xFFCEE7F0)
    private val onSecondaryContainerLight = Color(0xFF344A52)
    private val tertiaryLight = Color(0xFF585C7E)
    private val onTertiaryLight = Color(0xFFFFFFFF)
    private val tertiaryContainerLight = Color(0xFFDFE0FF)
    private val onTertiaryContainerLight = Color(0xFF414465)
    private val errorLight = Color(0xFFBA1A1A)
    private val onErrorLight = Color(0xFFFFFFFF)
    private val errorContainerLight = Color(0xFFFFDAD6)
    private val onErrorContainerLight = Color(0xFF93000A)
    private val backgroundLight = Color(0xFFF5FAFD)
    private val onBackgroundLight = Color(0xFF171C1E)
    private val surfaceLight = Color(0xFFF5FAFD)
    private val onSurfaceLight = Color(0xFF171C1E)
    private val surfaceVariantLight = Color(0xFFDBE4E8)
    private val onSurfaceVariantLight = Color(0xFF40484B)
    private val outlineLight = Color(0xFF70787C)
    private val outlineVariantLight = Color(0xFFBFC8CC)
    private val scrimLight = Color(0xFF000000)
    private val inverseSurfaceLight = Color(0xFF2C3133)
    private val inverseOnSurfaceLight = Color(0xFFECF1F4)
    private val inversePrimaryLight = Color(0xFF86D1E9)
    private val surfaceDimLight = Color(0xFFD6DBDD)
    private val surfaceBrightLight = Color(0xFFF5FAFD)
    private val surfaceContainerLowestLight = Color(0xFFFFFFFF)
    private val surfaceContainerLowLight = Color(0xFFEFF4F7)
    private val surfaceContainerLight = Color(0xFFEAEFF1)
    private val surfaceContainerHighLight = Color(0xFFE4E9EB)
    private val surfaceContainerHighestLight = Color(0xFFDEE3E6)

    private val primaryLightMediumContrast = Color(0xFF003C49)
    private val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
    private val primaryContainerLightMediumContrast = Color(0xFF21768C)
    private val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    private val secondaryLightMediumContrast = Color(0xFF233941)
    private val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
    private val secondaryContainerLightMediumContrast = Color(0xFF5A7179)
    private val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    private val tertiaryLightMediumContrast = Color(0xFF303453)
    private val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
    private val tertiaryContainerLightMediumContrast = Color(0xFF676B8D)
    private val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    private val errorLightMediumContrast = Color(0xFF740006)
    private val onErrorLightMediumContrast = Color(0xFFFFFFFF)
    private val errorContainerLightMediumContrast = Color(0xFFCF2C27)
    private val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
    private val backgroundLightMediumContrast = Color(0xFFF5FAFD)
    private val onBackgroundLightMediumContrast = Color(0xFF171C1E)
    private val surfaceLightMediumContrast = Color(0xFFF5FAFD)
    private val onSurfaceLightMediumContrast = Color(0xFF0C1214)
    private val surfaceVariantLightMediumContrast = Color(0xFFDBE4E8)
    private val onSurfaceVariantLightMediumContrast = Color(0xFF2F373B)
    private val outlineLightMediumContrast = Color(0xFF4B5457)
    private val outlineVariantLightMediumContrast = Color(0xFF666E72)
    private val scrimLightMediumContrast = Color(0xFF000000)
    private val inverseSurfaceLightMediumContrast = Color(0xFF2C3133)
    private val inverseOnSurfaceLightMediumContrast = Color(0xFFECF1F4)
    private val inversePrimaryLightMediumContrast = Color(0xFF86D1E9)
    private val surfaceDimLightMediumContrast = Color(0xFFC2C7CA)
    private val surfaceBrightLightMediumContrast = Color(0xFFF5FAFD)
    private val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
    private val surfaceContainerLowLightMediumContrast = Color(0xFFEFF4F7)
    private val surfaceContainerLightMediumContrast = Color(0xFFE4E9EB)
    private val surfaceContainerHighLightMediumContrast = Color(0xFFD8DEE0)
    private val surfaceContainerHighestLightMediumContrast = Color(0xFFCDD2D5)

    private val primaryLightHighContrast = Color(0xFF00313C)
    private val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
    private val primaryContainerLightHighContrast = Color(0xFF005061)
    private val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
    private val secondaryLightHighContrast = Color(0xFF192F36)
    private val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
    private val secondaryContainerLightHighContrast = Color(0xFF364C54)
    private val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
    private val tertiaryLightHighContrast = Color(0xFF262A48)
    private val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
    private val tertiaryContainerLightHighContrast = Color(0xFF434767)
    private val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
    private val errorLightHighContrast = Color(0xFF600004)
    private val onErrorLightHighContrast = Color(0xFFFFFFFF)
    private val errorContainerLightHighContrast = Color(0xFF98000A)
    private val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
    private val backgroundLightHighContrast = Color(0xFFF5FAFD)
    private val onBackgroundLightHighContrast = Color(0xFF171C1E)
    private val surfaceLightHighContrast = Color(0xFFF5FAFD)
    private val onSurfaceLightHighContrast = Color(0xFF000000)
    private val surfaceVariantLightHighContrast = Color(0xFFDBE4E8)
    private val onSurfaceVariantLightHighContrast = Color(0xFF000000)
    private val outlineLightHighContrast = Color(0xFF252D30)
    private val outlineVariantLightHighContrast = Color(0xFF424B4E)
    private val scrimLightHighContrast = Color(0xFF000000)
    private val inverseSurfaceLightHighContrast = Color(0xFF2C3133)
    private val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
    private val inversePrimaryLightHighContrast = Color(0xFF86D1E9)
    private val surfaceDimLightHighContrast = Color(0xFFB4BABC)
    private val surfaceBrightLightHighContrast = Color(0xFFF5FAFD)
    private val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
    private val surfaceContainerLowLightHighContrast = Color(0xFFECF1F4)
    private val surfaceContainerLightHighContrast = Color(0xFFDEE3E6)
    private val surfaceContainerHighLightHighContrast = Color(0xFFD0D5D8)
    private val surfaceContainerHighestLightHighContrast = Color(0xFFC2C7CA)

    private val primaryDark = Color(0xFF86D1E9)
    private val onPrimaryDark = Color(0xFF003642)
    private val primaryContainerDark = Color(0xFF004E5E)
    private val onPrimaryContainerDark = Color(0xFFB2EBFF)
    private val secondaryDark = Color(0xFFB2CAD3)
    private val onSecondaryDark = Color(0xFF1D343B)
    private val secondaryContainerDark = Color(0xFF344A52)
    private val onSecondaryContainerDark = Color(0xFFCEE7F0)
    private val tertiaryDark = Color(0xFFC1C4EB)
    private val onTertiaryDark = Color(0xFF2A2E4D)
    private val tertiaryContainerDark = Color(0xFF414465)
    private val onTertiaryContainerDark = Color(0xFFDFE0FF)
    private val errorDark = Color(0xFFFFB4AB)
    private val onErrorDark = Color(0xFF690005)
    private val errorContainerDark = Color(0xFF93000A)
    private val onErrorContainerDark = Color(0xFFFFDAD6)
    private val backgroundDark = Color(0xFF0F1416)
    private val onBackgroundDark = Color(0xFFDEE3E6)
    private val surfaceDark = Color(0xFF0F1416)
    private val onSurfaceDark = Color(0xFFDEE3E6)
    private val surfaceVariantDark = Color(0xFF40484B)
    private val onSurfaceVariantDark = Color(0xFFBFC8CC)
    private val outlineDark = Color(0xFF899296)
    private val outlineVariantDark = Color(0xFF40484B)
    private val scrimDark = Color(0xFF000000)
    private val inverseSurfaceDark = Color(0xFFDEE3E6)
    private val inverseOnSurfaceDark = Color(0xFF2C3133)
    private val inversePrimaryDark = Color(0xFF00677D)
    private val surfaceDimDark = Color(0xFF0F1416)
    private val surfaceBrightDark = Color(0xFF343A3C)
    private val surfaceContainerLowestDark = Color(0xFF090F11)
    private val surfaceContainerLowDark = Color(0xFF171C1E)
    private val surfaceContainerDark = Color(0xFF1B2022)
    private val surfaceContainerHighDark = Color(0xFF252B2D)
    private val surfaceContainerHighestDark = Color(0xFF303638)

    private val primaryDarkMediumContrast = Color(0xFF9EE7FF)
    private val onPrimaryDarkMediumContrast = Color(0xFF002A34)
    private val primaryContainerDarkMediumContrast = Color(0xFF4E9BB1)
    private val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
    private val secondaryDarkMediumContrast = Color(0xFFC8E0E9)
    private val onSecondaryDarkMediumContrast = Color(0xFF122930)
    private val secondaryContainerDarkMediumContrast = Color(0xFF7D949D)
    private val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
    private val tertiaryDarkMediumContrast = Color(0xFFD7DAFF)
    private val onTertiaryDarkMediumContrast = Color(0xFF1F2342)
    private val tertiaryContainerDarkMediumContrast = Color(0xFF8B8EB3)
    private val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
    private val errorDarkMediumContrast = Color(0xFFFFD2CC)
    private val onErrorDarkMediumContrast = Color(0xFF540003)
    private val errorContainerDarkMediumContrast = Color(0xFFFF5449)
    private val onErrorContainerDarkMediumContrast = Color(0xFF000000)
    private val backgroundDarkMediumContrast = Color(0xFF0F1416)
    private val onBackgroundDarkMediumContrast = Color(0xFFDEE3E6)
    private val surfaceDarkMediumContrast = Color(0xFF0F1416)
    private val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
    private val surfaceVariantDarkMediumContrast = Color(0xFF40484B)
    private val onSurfaceVariantDarkMediumContrast = Color(0xFFD5DEE1)
    private val outlineDarkMediumContrast = Color(0xFFABB3B7)
    private val outlineVariantDarkMediumContrast = Color(0xFF899295)
    private val scrimDarkMediumContrast = Color(0xFF000000)
    private val inverseSurfaceDarkMediumContrast = Color(0xFFDEE3E6)
    private val inverseOnSurfaceDarkMediumContrast = Color(0xFF252B2D)
    private val inversePrimaryDarkMediumContrast = Color(0xFF004F60)
    private val surfaceDimDarkMediumContrast = Color(0xFF0F1416)
    private val surfaceBrightDarkMediumContrast = Color(0xFF404548)
    private val surfaceContainerLowestDarkMediumContrast = Color(0xFF04080A)
    private val surfaceContainerLowDarkMediumContrast = Color(0xFF191E20)
    private val surfaceContainerDarkMediumContrast = Color(0xFF23292B)
    private val surfaceContainerHighDarkMediumContrast = Color(0xFF2E3336)
    private val surfaceContainerHighestDarkMediumContrast = Color(0xFF393F41)

    private val primaryDarkHighContrast = Color(0xFFD9F5FF)
    private val onPrimaryDarkHighContrast = Color(0xFF000000)
    private val primaryContainerDarkHighContrast = Color(0xFF82CDE5)
    private val onPrimaryContainerDarkHighContrast = Color(0xFF000D12)
    private val secondaryDarkHighContrast = Color(0xFFDCF4FD)
    private val onSecondaryDarkHighContrast = Color(0xFF000000)
    private val secondaryContainerDarkHighContrast = Color(0xFFAFC7CF)
    private val onSecondaryContainerDarkHighContrast = Color(0xFF000D12)
    private val tertiaryDarkHighContrast = Color(0xFFF0EEFF)
    private val onTertiaryDarkHighContrast = Color(0xFF000000)
    private val tertiaryContainerDarkHighContrast = Color(0xFFBDC0E7)
    private val onTertiaryContainerDarkHighContrast = Color(0xFF050826)
    private val errorDarkHighContrast = Color(0xFFFFECE9)
    private val onErrorDarkHighContrast = Color(0xFF000000)
    private val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
    private val onErrorContainerDarkHighContrast = Color(0xFF220001)
    private val backgroundDarkHighContrast = Color(0xFF0F1416)
    private val onBackgroundDarkHighContrast = Color(0xFFDEE3E6)
    private val surfaceDarkHighContrast = Color(0xFF0F1416)
    private val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
    private val surfaceVariantDarkHighContrast = Color(0xFF40484B)
    private val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
    private val outlineDarkHighContrast = Color(0xFFE9F1F5)
    private val outlineVariantDarkHighContrast = Color(0xFFBBC4C8)
    private val scrimDarkHighContrast = Color(0xFF000000)
    private val inverseSurfaceDarkHighContrast = Color(0xFFDEE3E6)
    private val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
    private val inversePrimaryDarkHighContrast = Color(0xFF004F60)
    private val surfaceDimDarkHighContrast = Color(0xFF0F1416)
    private val surfaceBrightDarkHighContrast = Color(0xFF4B5153)
    private val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
    private val surfaceContainerLowDarkHighContrast = Color(0xFF1B2022)
    private val surfaceContainerDarkHighContrast = Color(0xFF2C3133)
    private val surfaceContainerHighDarkHighContrast = Color(0xFF373C3E)
    private val surfaceContainerHighestDarkHighContrast = Color(0xFF42484A)

    override val lightScheme = lightColorScheme(
        primary = primaryLight,
        onPrimary = onPrimaryLight,
        primaryContainer = primaryContainerLight,
        onPrimaryContainer = onPrimaryContainerLight,
        secondary = secondaryLight,
        onSecondary = onSecondaryLight,
        secondaryContainer = secondaryContainerLight,
        onSecondaryContainer = onSecondaryContainerLight,
        tertiary = tertiaryLight,
        onTertiary = onTertiaryLight,
        tertiaryContainer = tertiaryContainerLight,
        onTertiaryContainer = onTertiaryContainerLight,
        error = errorLight,
        onError = onErrorLight,
        errorContainer = errorContainerLight,
        onErrorContainer = onErrorContainerLight,
        background = backgroundLight,
        onBackground = onBackgroundLight,
        surface = surfaceLight,
        onSurface = onSurfaceLight,
        surfaceVariant = surfaceVariantLight,
        onSurfaceVariant = onSurfaceVariantLight,
        outline = outlineLight,
        outlineVariant = outlineVariantLight,
        scrim = scrimLight,
        inverseSurface = inverseSurfaceLight,
        inverseOnSurface = inverseOnSurfaceLight,
        inversePrimary = inversePrimaryLight,
        surfaceDim = surfaceDimLight,
        surfaceBright = surfaceBrightLight,
        surfaceContainerLowest = surfaceContainerLowestLight,
        surfaceContainerLow = surfaceContainerLowLight,
        surfaceContainer = surfaceContainerLight,
        surfaceContainerHigh = surfaceContainerHighLight,
        surfaceContainerHighest = surfaceContainerHighestLight,
    )

    override val darkScheme = darkColorScheme(
        primary = primaryDark,
        onPrimary = onPrimaryDark,
        primaryContainer = primaryContainerDark,
        onPrimaryContainer = onPrimaryContainerDark,
        secondary = secondaryDark,
        onSecondary = onSecondaryDark,
        secondaryContainer = secondaryContainerDark,
        onSecondaryContainer = onSecondaryContainerDark,
        tertiary = tertiaryDark,
        onTertiary = onTertiaryDark,
        tertiaryContainer = tertiaryContainerDark,
        onTertiaryContainer = onTertiaryContainerDark,
        error = errorDark,
        onError = onErrorDark,
        errorContainer = errorContainerDark,
        onErrorContainer = onErrorContainerDark,
        background = backgroundDark,
        onBackground = onBackgroundDark,
        surface = surfaceDark,
        onSurface = onSurfaceDark,
        surfaceVariant = surfaceVariantDark,
        onSurfaceVariant = onSurfaceVariantDark,
        outline = outlineDark,
        outlineVariant = outlineVariantDark,
        scrim = scrimDark,
        inverseSurface = inverseSurfaceDark,
        inverseOnSurface = inverseOnSurfaceDark,
        inversePrimary = inversePrimaryDark,
        surfaceDim = surfaceDimDark,
        surfaceBright = surfaceBrightDark,
        surfaceContainerLowest = surfaceContainerLowestDark,
        surfaceContainerLow = surfaceContainerLowDark,
        surfaceContainer = surfaceContainerDark,
        surfaceContainerHigh = surfaceContainerHighDark,
        surfaceContainerHighest = surfaceContainerHighestDark,
    )

    override val mediumContrastLightColorScheme = lightColorScheme(
        primary = primaryLightMediumContrast,
        onPrimary = onPrimaryLightMediumContrast,
        primaryContainer = primaryContainerLightMediumContrast,
        onPrimaryContainer = onPrimaryContainerLightMediumContrast,
        secondary = secondaryLightMediumContrast,
        onSecondary = onSecondaryLightMediumContrast,
        secondaryContainer = secondaryContainerLightMediumContrast,
        onSecondaryContainer = onSecondaryContainerLightMediumContrast,
        tertiary = tertiaryLightMediumContrast,
        onTertiary = onTertiaryLightMediumContrast,
        tertiaryContainer = tertiaryContainerLightMediumContrast,
        onTertiaryContainer = onTertiaryContainerLightMediumContrast,
        error = errorLightMediumContrast,
        onError = onErrorLightMediumContrast,
        errorContainer = errorContainerLightMediumContrast,
        onErrorContainer = onErrorContainerLightMediumContrast,
        background = backgroundLightMediumContrast,
        onBackground = onBackgroundLightMediumContrast,
        surface = surfaceLightMediumContrast,
        onSurface = onSurfaceLightMediumContrast,
        surfaceVariant = surfaceVariantLightMediumContrast,
        onSurfaceVariant = onSurfaceVariantLightMediumContrast,
        outline = outlineLightMediumContrast,
        outlineVariant = outlineVariantLightMediumContrast,
        scrim = scrimLightMediumContrast,
        inverseSurface = inverseSurfaceLightMediumContrast,
        inverseOnSurface = inverseOnSurfaceLightMediumContrast,
        inversePrimary = inversePrimaryLightMediumContrast,
        surfaceDim = surfaceDimLightMediumContrast,
        surfaceBright = surfaceBrightLightMediumContrast,
        surfaceContainerLowest = surfaceContainerLowestLightMediumContrast,
        surfaceContainerLow = surfaceContainerLowLightMediumContrast,
        surfaceContainer = surfaceContainerLightMediumContrast,
        surfaceContainerHigh = surfaceContainerHighLightMediumContrast,
        surfaceContainerHighest = surfaceContainerHighestLightMediumContrast,
    )

    override val highContrastLightColorScheme = lightColorScheme(
        primary = primaryLightHighContrast,
        onPrimary = onPrimaryLightHighContrast,
        primaryContainer = primaryContainerLightHighContrast,
        onPrimaryContainer = onPrimaryContainerLightHighContrast,
        secondary = secondaryLightHighContrast,
        onSecondary = onSecondaryLightHighContrast,
        secondaryContainer = secondaryContainerLightHighContrast,
        onSecondaryContainer = onSecondaryContainerLightHighContrast,
        tertiary = tertiaryLightHighContrast,
        onTertiary = onTertiaryLightHighContrast,
        tertiaryContainer = tertiaryContainerLightHighContrast,
        onTertiaryContainer = onTertiaryContainerLightHighContrast,
        error = errorLightHighContrast,
        onError = onErrorLightHighContrast,
        errorContainer = errorContainerLightHighContrast,
        onErrorContainer = onErrorContainerLightHighContrast,
        background = backgroundLightHighContrast,
        onBackground = onBackgroundLightHighContrast,
        surface = surfaceLightHighContrast,
        onSurface = onSurfaceLightHighContrast,
        surfaceVariant = surfaceVariantLightHighContrast,
        onSurfaceVariant = onSurfaceVariantLightHighContrast,
        outline = outlineLightHighContrast,
        outlineVariant = outlineVariantLightHighContrast,
        scrim = scrimLightHighContrast,
        inverseSurface = inverseSurfaceLightHighContrast,
        inverseOnSurface = inverseOnSurfaceLightHighContrast,
        inversePrimary = inversePrimaryLightHighContrast,
        surfaceDim = surfaceDimLightHighContrast,
        surfaceBright = surfaceBrightLightHighContrast,
        surfaceContainerLowest = surfaceContainerLowestLightHighContrast,
        surfaceContainerLow = surfaceContainerLowLightHighContrast,
        surfaceContainer = surfaceContainerLightHighContrast,
        surfaceContainerHigh = surfaceContainerHighLightHighContrast,
        surfaceContainerHighest = surfaceContainerHighestLightHighContrast,
    )

    override val mediumContrastDarkColorScheme = darkColorScheme(
        primary = primaryDarkMediumContrast,
        onPrimary = onPrimaryDarkMediumContrast,
        primaryContainer = primaryContainerDarkMediumContrast,
        onPrimaryContainer = onPrimaryContainerDarkMediumContrast,
        secondary = secondaryDarkMediumContrast,
        onSecondary = onSecondaryDarkMediumContrast,
        secondaryContainer = secondaryContainerDarkMediumContrast,
        onSecondaryContainer = onSecondaryContainerDarkMediumContrast,
        tertiary = tertiaryDarkMediumContrast,
        onTertiary = onTertiaryDarkMediumContrast,
        tertiaryContainer = tertiaryContainerDarkMediumContrast,
        onTertiaryContainer = onTertiaryContainerDarkMediumContrast,
        error = errorDarkMediumContrast,
        onError = onErrorDarkMediumContrast,
        errorContainer = errorContainerDarkMediumContrast,
        onErrorContainer = onErrorContainerDarkMediumContrast,
        background = backgroundDarkMediumContrast,
        onBackground = onBackgroundDarkMediumContrast,
        surface = surfaceDarkMediumContrast,
        onSurface = onSurfaceDarkMediumContrast,
        surfaceVariant = surfaceVariantDarkMediumContrast,
        onSurfaceVariant = onSurfaceVariantDarkMediumContrast,
        outline = outlineDarkMediumContrast,
        outlineVariant = outlineVariantDarkMediumContrast,
        scrim = scrimDarkMediumContrast,
        inverseSurface = inverseSurfaceDarkMediumContrast,
        inverseOnSurface = inverseOnSurfaceDarkMediumContrast,
        inversePrimary = inversePrimaryDarkMediumContrast,
        surfaceDim = surfaceDimDarkMediumContrast,
        surfaceBright = surfaceBrightDarkMediumContrast,
        surfaceContainerLowest = surfaceContainerLowestDarkMediumContrast,
        surfaceContainerLow = surfaceContainerLowDarkMediumContrast,
        surfaceContainer = surfaceContainerDarkMediumContrast,
        surfaceContainerHigh = surfaceContainerHighDarkMediumContrast,
        surfaceContainerHighest = surfaceContainerHighestDarkMediumContrast,
    )

    override val highContrastDarkColorScheme = darkColorScheme(
        primary = primaryDarkHighContrast,
        onPrimary = onPrimaryDarkHighContrast,
        primaryContainer = primaryContainerDarkHighContrast,
        onPrimaryContainer = onPrimaryContainerDarkHighContrast,
        secondary = secondaryDarkHighContrast,
        onSecondary = onSecondaryDarkHighContrast,
        secondaryContainer = secondaryContainerDarkHighContrast,
        onSecondaryContainer = onSecondaryContainerDarkHighContrast,
        tertiary = tertiaryDarkHighContrast,
        onTertiary = onTertiaryDarkHighContrast,
        tertiaryContainer = tertiaryContainerDarkHighContrast,
        onTertiaryContainer = onTertiaryContainerDarkHighContrast,
        error = errorDarkHighContrast,
        onError = onErrorDarkHighContrast,
        errorContainer = errorContainerDarkHighContrast,
        onErrorContainer = onErrorContainerDarkHighContrast,
        background = backgroundDarkHighContrast,
        onBackground = onBackgroundDarkHighContrast,
        surface = surfaceDarkHighContrast,
        onSurface = onSurfaceDarkHighContrast,
        surfaceVariant = surfaceVariantDarkHighContrast,
        onSurfaceVariant = onSurfaceVariantDarkHighContrast,
        outline = outlineDarkHighContrast,
        outlineVariant = outlineVariantDarkHighContrast,
        scrim = scrimDarkHighContrast,
        inverseSurface = inverseSurfaceDarkHighContrast,
        inverseOnSurface = inverseOnSurfaceDarkHighContrast,
        inversePrimary = inversePrimaryDarkHighContrast,
        surfaceDim = surfaceDimDarkHighContrast,
        surfaceBright = surfaceBrightDarkHighContrast,
        surfaceContainerLowest = surfaceContainerLowestDarkHighContrast,
        surfaceContainerLow = surfaceContainerLowDarkHighContrast,
        surfaceContainer = surfaceContainerDarkHighContrast,
        surfaceContainerHigh = surfaceContainerHighDarkHighContrast,
        surfaceContainerHighest = surfaceContainerHighestDarkHighContrast,
    )
}